import type { Restaurant } from "@/types";

interface UserPreferences {
  cuisines?: string[];
  vibe?: string[];
  dietary?: string[];
  budget?: "low" | "mid" | "high";
  location?: string;
}

interface Candidate {
  restaurant: Restaurant;
  score: number;
}

export const RESTAURANTS: Restaurant[] = [
  {
    id: "6627a5003e6f5bad735de38b",
    name: "Al Bayt - Palace Downtown",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["Middle Eastern", "Arabic"],
    price: "high",
    vibe: ["upscale", "elegant", "romantic"],
    dietary: ["halal", "vegetarian-friendly", "gluten-free-options"],
    rating: 4.5,
    highlights: ["Afternoon tea", "Fountain views", "Arabic breakfast"],
    bookingAvailable: true,
  },
  {
    id: "66054abe14c1398684ac4b1a",
    name: "Al Fanar Restaurant & Cafe - Expo City",
    area: "Al Wasl",
    city: "Dubai",
    cuisines: ["Emirati", "Middle Eastern"],
    price: "mid",
    vibe: ["casual", "family-friendly", "traditional"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Traditional Emirati cuisine", "Heritage setting"],
    bookingAvailable: true,
  },
  {
    id: "67879ed5ac31fa8b4dfeabed",
    name: "Al Farah Gourmet Butchery & Restaurant",
    area: "Al Wasl",
    city: "Dubai",
    cuisines: ["Lebanese", "Middle Eastern"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Premium meats", "Mixed grills"],
    bookingAvailable: true,
  },
  {
    id: "6627a4f89b30c4d10cadb3c3",
    name: "Al Wasl Plaza Cafe",
    area: "Expo City",
    city: "Dubai",
    cuisines: ["Cafe", "International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: false,
    discountCode: "PURAVIDA10",
  },
  {
    id: "6787a01c9b410af405a81e65",
    name: "Ala Turkish Restaurant",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Turkish", "Middle Eastern", "French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "6825e1742af799529a171d7f",
    name: "Alba Restaurant Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76005b073a6d60fbc29c7",
    name: "Amal Restaurant Armani Hotel",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly", "gluten-free-options"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7606c6ccd3a5de890733f",
    name: "Armani / Mediterraneo",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Mediterranean"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly", "gluten-free-options"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7608982a10b35feb6c764",
    name: "Armani Hashi",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["Japanese"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly", "gluten-free-options"],
    rating: 4.5,
    highlights: ["Fresh sushi", "Sake selection"],
    bookingAvailable: true,
  },
  {
    id: "63d7608722a4d30bedb77eee",
    name: "ArmaniLounge",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant", "lively"],
    dietary: ["vegetarian-friendly", "gluten-free-options"],
    rating: 4.5,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d760776584a6f5a78da69c",
    name: "Asha's Restaurants",
    area: "Oud Metha",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76069a69626d098199433",
    name: "Asia Asia Business Bay",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Pan-Asian"],
    price: "high",
    vibe: ["upscale", "modern", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Sushi", "Dim sum", "Pan-Asian cuisine"],
    bookingAvailable: true,
  },
  {
    id: "63d7600712ce4fe67e44592d",
    name: "Asil Dubai  Turkish, Lebanese and Moroccan Restaurant",
    area: "The Walk",
    city: "Dubai",
    cuisines: ["Turkish", "Middle Eastern", "Lebanese", "Moroccan"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7604d10ab8fc8914355aa",
    name: "BAI Bar  Terrace",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d75f80a830f41be69e6f45",
    name: "Bakala Jooos",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d7604a51567ae1219a3891",
    name: "Bebemos Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760e5c8b6684c4108e29f",
    name: "Beef Bistro",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French", "Steakhouse"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d76016006b137cba0c5916",
    name: "Belgian Beer Cafe Madinat Jumeirah",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["Belgian", "European"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7600ff5325b73ebf84c5a",
    name: "Bella Restaurant & Lounge",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["lively", "modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list", "Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "67879e77c06593cf93f31d9f",
    name: "Biella Café Pizzeria Ristorante",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Italian", "Pizza", "French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Authentic pasta", "Wine selection", "French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "6825e1c1ed962a810ce71deb",
    name: "Bisou Restaurant Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fd150176f5861bfadf6",
    name: "Blue Seafood Asia",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Seafood", "Asian"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fbb8d2657c939a77343",
    name: "BOCA",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["Mediterranean", "Spanish"],
    price: "high",
    vibe: ["upscale", "modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Mediterranean cuisine", "DIFC location"],
    bookingAvailable: true,
  },
  {
    id: "6825e37a574bcfd29964305b",
    name: "Bombay Borough",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["Indian"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6787a0d001eed66f44a74ed5",
    name: "Brunch City",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7607061fed3542b823738",
    name: "C Restaurant",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760a2a10e291023d61f0f",
    name: "Caia Caf  Restaurant",
    area: "Al Wasl",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fbcc5aa18c4eb5f712d",
    name: "Cara",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7608707673df4d82a1771",
    name: "Cargo Dubai",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "63d75f86443a4c43b48fd107",
    name: "Carluccio's The Dubai Mall",
    area: "Boardwalk",
    city: "Dubai",
    cuisines: ["Italian"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Authentic pasta", "Wine selection"],
    bookingAvailable: true,
  },
  {
    id: "63d75fa4e9a61e344b7d09bf",
    name: "Celebrities",
    area: "King Salman Bin Abdulaziz Al Saud St - Dubai - United Arab Emirates",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6627a501c81013235d9d4f2f",
    name: "Circle Cafe Media City",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d760001a9bab5328918d7d",
    name: "Cleo Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Mediterranean", "Middle Eastern"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67879f8a8e16a51e29327692",
    name: "Colt",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7605436104c3bb86c4e8b",
    name: "Couqley French Bistro & Bar",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual", "lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French bistro", "Wine selection"],
    bookingAvailable: true,
  },
  {
    id: "64674e609c4b67d619a478a1",
    name: "Couqley French Brasserie Downtown Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual", "lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French bistro", "Wine selection"],
    bookingAvailable: true,
  },
  {
    id: "63d75fc573d63fe210881072",
    name: "Eauzone",
    area: "King Salman Bin Abdulaziz Al Saud St - Dubai - United Arab Emirates",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6825e1ffc2ad56771a10a5be",
    name: "Ewaan",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760b0e63c14cc67b64925",
    name: "Ewaan - Palace Downtown",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly", "gluten-free-options"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6787a0af609c48b6cec30e31",
    name: "Fai Lounge",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d75fd2d4f26d08a67c816f",
    name: "GARTH Restaurant & Cafe",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Cafe", "International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760b6468fd95f8657420b",
    name: "Ginter",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "674085a3a6103d107912385e",
    name: "Girl & The Goose",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75ffb7fee2f110347130c",
    name: "Gourmandises",
    area: "Garhoud",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6526319807f950ea55d3284d",
    name: "Günaydin",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Turkish"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67879dca6d5d1050cead2035",
    name: "HideOut Al Barari",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d75f8a61b3f8e33338ac21",
    name: "Hudson Tavern Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["American"],
    price: "mid",
    vibe: ["casual", "lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7609e993710b257c9ff2d",
    name: "Jules",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67879dfa27dbbd8b5476d662",
    name: "Kasibeyaz Dubai Hills Mall",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Turkish"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75f859b9547f0d8de4de2",
    name: "Katsuya Dubai",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["Japanese"],
    price: "mid",
    vibe: ["modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Fresh sushi", "Sake selection"],
    bookingAvailable: true,
  },
  {
    id: "63d7605a2cae1060d3d013a6",
    name: "Kiku",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Japanese"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Fresh sushi", "Sake selection"],
    bookingAvailable: true,
  },
  {
    id: "65e1e77d00b59237687743d1",
    name: "L'etoile Restaurant & Cafe",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d7607a35be1042104f724f",
    name: "La Casa del Tango",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["French"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d7600c10f551f25a16ceb5",
    name: "La Fontana Restaurant",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list", "Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "67804119c61aa54a64fb8f65",
    name: "La Nina Restaurant Ltd",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "67804237b10fe90710cc9cde",
    name: "Latitude 25",
    area: "Garhoud",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6787a05abfa436fb21851add",
    name: "Le Burger ( Dubai )",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French", "American", "Burgers"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d76021cc1010514344e2d9",
    name: "Le Petit Belge",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French", "Belgian"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "67879dc24875f61a0e4813fe",
    name: "LILA Wood-Fired Taqueria",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["French", "Mexican"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "678040bc49c89ab079d2cbb6",
    name: "Living Room Restaurant and Lounge",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant", "lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d7607354bff27b54a25e8a",
    name: "Lock, Stock  Barrel",
    area: "Tecom",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "64677b484e1ae86fa23418e1",
    name: "Lock, Stock & Barrel Business Bay",
    area: "Business Bay",
    city: "Business Bay",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d760027f1f555372e5fcdb",
    name: "Long Yin",
    area: "Garhoud",
    city: "Dubai",
    cuisines: ["Chinese"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6627a40e12d6807fa5bd9c03",
    name: "Luna Dubai",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant", "romantic"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7601b75298fbee955b9a1",
    name: "Maison Mathis Arabian Ranches",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75ffcbe3610bb526734dd",
    name: "Makar",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["romantic", "modern", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "63d75fb4eaf20e6c3f1eed32",
    name: "Mama Zonia",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "658ae2cb3f61b169566b447f",
    name: "Meat Moot Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fd61105c3406e161b6a",
    name: "Mercury Lounge",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["romantic", "lively", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Beach views", "Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d76059a684810406a3a835",
    name: "Mint Leaf of London Dubai",
    area: "DIFC",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["upscale", "elegant"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "64f67e5a5493519468726e3b",
    name: "Miracolo Restaurant and Bar",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Italian"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Authentic pasta", "Wine selection", "Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "63d75f8fbd271296df14efb2",
    name: "MITRA - Indian Fusion Bistro",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French", "Indian", "Fusion"],
    price: "mid",
    vibe: ["casual", "modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d75f9b958ae9a1dbd275a7",
    name: "Myrra Restaurant",
    area: "Palm Jumeirah",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "66a8da95b6a2c21027cc72bf",
    name: "Mythos Urban Greek Eatery",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Greek"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67aecfb1839de8c3d3b83e73",
    name: "Nightjar Coffee Roasters",
    area: "Alserkal Avenue",
    city: "Dubai",
    cuisines: ["Cafe", "International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76047f1012227b35a8ec7",
    name: "North Miznon Dubai",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "63d75fa7e61c757c108b8ad4",
    name: "Off the Wall",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76088783fdb212510833c",
    name: "Open Sesame",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fa4695d04d1010afcbb",
    name: "Orange Feels Bar",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "67879ebbc7310524cac281c4",
    name: "Origins",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67879ef0d8d3298fe19cb16d",
    name: "Origins at Vida Creek Beach",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "657917565e9e8b21a1dfbe94",
    name: "Parker's",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "66c732053b78fcc6dabdbf65",
    name: "Pili Pili BBQ House Restaurant",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "65f872f9d1b1e95c6f2ffba4",
    name: "Pitfire Pizza",
    area: "Business Park-1",
    city: "Dubai",
    cuisines: ["Italian", "Pizza"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Authentic pasta", "Wine selection"],
    bookingAvailable: true,
  },
  {
    id: "6825e180588e9e8a31900103",
    name: "PLAY Restaurant & Lounge Bar",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "661173df27e1ddf638e83d3f",
    name: "PXB",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7600ba83d6c010b295a2c",
    name: "Reform Social  Grill",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Steakhouse", "American", "British"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67108acd0be1733d5b35bd54",
    name: "Sagra Italian Pastificio",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["Italian", "Pasta"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Authentic pasta", "Wine selection"],
    bookingAvailable: true,
  },
  {
    id: "6491ab071b9a7e1e74ff2a69",
    name: "Salmon Guru Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67879d44f810b35c74bb910e",
    name: "Sayf",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "67879e0b4a734b2fac5b8a21",
    name: "Sayf",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7607c75bf54a6b75eac25",
    name: "Sea Fu Restaurant and Bar",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["Seafood", "Asian"],
    price: "mid",
    vibe: ["romantic", "lively", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Beach views", "Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "67836407de8fac7bd12671a4",
    name: "Senecio Restaurant & Lounge",
    area: "The Walk",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "68060a3f711d45961c4d6660",
    name: "Shai Salon & Terrace",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fab54659e2e8fc94c15",
    name: "Siraj Restaurant",
    area: "Downtown",
    city: "Dubai",
    cuisines: ["Middle Eastern"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760b71ca8d77964c680d8",
    name: "Social Distrikt",
    area: "Palm Jumeirah",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76050f2477931d5f1ca78",
    name: "Soulgreen",
    area: "Ras Al Khor",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7607661084ff6bc2d8d75",
    name: "STK Dubai JBR",
    area: "The Walk",
    city: "Dubai",
    cuisines: ["Steakhouse", "American"],
    price: "high",
    vibe: ["upscale", "lively", "modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Premium steaks", "Lounge atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6825e337cc39bc47bf7f66a4",
    name: "Tagine",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Moroccan", "Middle Eastern"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6627a50b0f71688713631012",
    name: "Talhan",
    area: "Expo City",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75f990133627f427dfbf8",
    name: "TAN CHA",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6825e32a5387085963d4f431",
    name: "Tent Jumeirah Restaurant",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "64e7e62cd34aaff3e7550d1a",
    name: "The 305",
    area: "The Club - Palm West Beach",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["romantic", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Beach views"],
    bookingAvailable: true,
  },
  {
    id: "63d75f94f3d34f4fba10cb5f",
    name: "The Artisan Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "high",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.5,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760107378595e6da51130",
    name: "The Beach Bar & Grill",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["Steakhouse", "American"],
    price: "mid",
    vibe: ["lively", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views", "Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "6627a503be26dfd109d10071",
    name: "The Citronelle Club",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d75fdffe3bd80b45bed64d",
    name: "The Croft",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "6602f5d5b1de57c767231b8f",
    name: "The Daily at Rove Expo City",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fd6f7a5d74c635d82df",
    name: "The Dubliner's",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fb86f33b9b210e1c0e1",
    name: "The Larder Canal View",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["modern"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75f9aaf6f559e0a637399",
    name: "The Larder Waterfront",
    area: "Business Bay",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["romantic", "modern", "waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
  {
    id: "63d75ff8a53a835ce574fbe5",
    name: "The Lighthouse MOE",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d760be0a329a2b24aa106a",
    name: "The MAINE Land Brasserie, Business Bay Dubai",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d760c10e7da93ac8c07e4b",
    name: "The MAINE Oyster Bar & Grill",
    area: "JBR",
    city: "Dubai",
    cuisines: ["Steakhouse", "American"],
    price: "mid",
    vibe: ["lively"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Cocktail menu"],
    bookingAvailable: true,
  },
  {
    id: "65aa857da31f31383f03404d",
    name: "The Pods",
    area: "Bluewaters",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75f9289102870bd10159f",
    name: "The Restaurant - Address Grand Creek Harbour",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7607468caf84654e81177",
    name: "Thiptara",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Thai"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d7602d729c1185c0724891",
    name: "Ting Irie",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76085e1e2104f010c3eda",
    name: "TOKYO TOKYO CENTRAL",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Japanese"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Fresh sushi", "Sake selection"],
    bookingAvailable: true,
  },
  {
    id: "63d7602369f63c837af5b98b",
    name: "Turkish Village",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["Turkish", "Middle Eastern"],
    price: "mid",
    vibe: ["romantic", "waterfront"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Beach views"],
    bookingAvailable: true,
  },
  {
    id: "63d75fafd5f2dfbbf770fc4f",
    name: "Turkish Village DFC",
    area: "Festival City",
    city: "Dubai",
    cuisines: ["Turkish", "Middle Eastern"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["halal", "vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6627a416666dd11b81010abc",
    name: "Turquoise Restaurant",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d76083a3e21d727f910de9",
    name: "Vaga Restaurant",
    area: "Bluewaters",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "646e45065fe110a10e17fb3e",
    name: "Verde Beach Jumeirah Beach",
    area: "Jumeirah",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "65b500a9b5e5d214e2289e79",
    name: "Villa Naas",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["French"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["French classics", "Wine list"],
    bookingAvailable: true,
  },
  {
    id: "63d75f90167124c8884ce710",
    name: "Wabi Sabi Restaurant",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Japanese"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Fresh sushi", "Sake selection"],
    bookingAvailable: true,
  },
  {
    id: "63d75fd373312710b0b35397",
    name: "Yalumba",
    area: "Garhoud",
    city: "Dubai",
    cuisines: ["International"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "6787a0d24e5d189a86dd8c5d",
    name: "Ying Ji Dim Sum（Move to Next door Yun Xi Lou)",
    area: "Dubai",
    city: "Dubai",
    cuisines: ["Chinese", "Dim Sum"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fa7c8401f8414dd9048",
    name: "Yum! Asian Restaurant",
    area: "Deira",
    city: "Dubai",
    cuisines: ["Asian"],
    price: "mid",
    vibe: ["casual"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Quality cuisine", "Great atmosphere"],
    bookingAvailable: true,
  },
  {
    id: "63d75fb058d8500a2dc369bd",
    name: "Zafran - Dubai Marina Mall",
    area: "Dubai Marina",
    city: "Dubai",
    cuisines: ["Indian"],
    price: "mid",
    vibe: ["waterfront"],
    dietary: ["vegetarian-friendly"],
    rating: 4.3,
    highlights: ["Waterfront views"],
    bookingAvailable: true,
  },
];

/**
 * Get all unique cities from the restaurant database
 */
export function getAvailableCities(): string[] {
  const cities = new Set<string>();
  RESTAURANTS.forEach((r) => cities.add(r.city));
  return Array.from(cities).sort();
}

/**
 * Get all unique cuisines from the restaurant database
 */
export function getAvailableCuisines(): string[] {
  const cuisines = new Set<string>();
  RESTAURANTS.forEach((r) => r.cuisines.forEach((c) => cuisines.add(c)));
  return Array.from(cuisines).sort();
}

/**
 * Get all unique vibes from the restaurant database
 */
export function getAvailableVibes(): string[] {
  const vibes = new Set<string>();
  RESTAURANTS.forEach((r) => r.vibe.forEach((v) => vibes.add(v)));
  return Array.from(vibes).sort();
}

/**
 * Get all unique dietary options from the restaurant database
 */
export function getAvailableDietary(): string[] {
  const dietary = new Set<string>();
  RESTAURANTS.forEach((r) => r.dietary.forEach((d) => dietary.add(d)));
  return Array.from(dietary).sort();
}

/**
 * Check if a location (city or area) exists in the database
 * Returns true if the location matches any city or area in the database
 */
export function isLocationValid(location: string): boolean {
  if (!location || location.trim() === "") return false;
  const locationLower = location.toLowerCase().trim();
  
  return RESTAURANTS.some((r) => 
    r.city.toLowerCase().includes(locationLower) ||
    locationLower.includes(r.city.toLowerCase()) ||
    r.area.toLowerCase().includes(locationLower) ||
    locationLower.includes(r.area.toLowerCase())
  );
}

/**
 * Check if a cuisine exists in the database (fuzzy matching)
 * Returns true if the cuisine matches any cuisine in the database
 */
export function isCuisineValid(cuisine: string): boolean {
  if (!cuisine || cuisine.trim() === "") return false;
  const cuisineLower = cuisine.toLowerCase().trim();
  const availableCuisines = getAvailableCuisines();
  
  return availableCuisines.some((c) => 
    c.toLowerCase().includes(cuisineLower) ||
    cuisineLower.includes(c.toLowerCase())
  );
}

/**
 * Check if a vibe exists in the database (fuzzy matching)
 * Returns true if the vibe matches any vibe in the database
 */
export function isVibeValid(vibe: string): boolean {
  if (!vibe || vibe.trim() === "") return false;
  const vibeLower = vibe.toLowerCase().trim();
  const availableVibes = getAvailableVibes();
  
  return availableVibes.some((v) => 
    v.toLowerCase().includes(vibeLower) ||
    vibeLower.includes(v.toLowerCase())
  );
}

/**
 * Check if a dietary option exists in the database (fuzzy matching)
 * Returns true if the dietary option matches any dietary option in the database
 */
export function isDietaryValid(dietary: string): boolean {
  if (!dietary || dietary.trim() === "") return false;
  const dietaryLower = dietary.toLowerCase().trim();
  const availableDietary = getAvailableDietary();
  
  return availableDietary.some((d) => 
    d.toLowerCase().includes(dietaryLower) ||
    dietaryLower.includes(d.toLowerCase())
  );
}

/**
 * Filter out invalid cuisines and return only valid ones
 */
export function filterValidCuisines(cuisines: string[]): { valid: string[]; invalid: string[] } {
  const valid: string[] = [];
  const invalid: string[] = [];
  
  cuisines.forEach((c) => {
    if (isCuisineValid(c)) {
      valid.push(c);
    } else {
      invalid.push(c);
    }
  });
  
  return { valid, invalid };
}

/**
 * Filter out invalid vibes and return only valid ones
 */
export function filterValidVibes(vibes: string[]): { valid: string[]; invalid: string[] } {
  const valid: string[] = [];
  const invalid: string[] = [];
  
  vibes.forEach((v) => {
    if (isVibeValid(v)) {
      valid.push(v);
    } else {
      invalid.push(v);
    }
  });
  
  return { valid, invalid };
}

/**
 * Filter out invalid dietary options and return only valid ones
 */
export function filterValidDietary(dietary: string[]): { valid: string[]; invalid: string[] } {
  const valid: string[] = [];
  const invalid: string[] = [];
  
  dietary.forEach((d) => {
    if (isDietaryValid(d)) {
      valid.push(d);
    } else {
      invalid.push(d);
    }
  });
  
  return { valid, invalid };
}

/**
 * Find candidate restaurants based on user preferences
 * Returns top 5 ranked candidates with scores
 */
export function findCandidates(preferences: UserPreferences): Candidate[] {
  const candidates: Candidate[] = RESTAURANTS.map((restaurant) => {
    let score = 0;

    // Cuisine matching (+3 per match, but only if there's an actual match)
    if (preferences.cuisines && preferences.cuisines.length > 0) {
      const cuisineMatches = restaurant.cuisines.filter((c) =>
        preferences.cuisines!.some((pref) => {
          const cLower = c.toLowerCase();
          const prefLower = pref.toLowerCase();
          // Exact match or substring match (but be more strict)
          return cLower === prefLower || 
                 cLower.includes(prefLower) || 
                 prefLower.includes(cLower);
        })
      );
      // Only add score if there's a match - don't give points for no matches
      if (cuisineMatches.length > 0) {
        score += cuisineMatches.length * 3;
      } else {
        // Penalize restaurants that don't match the requested cuisine
        score -= 5;
      }
    }

    // Vibe matching (+2 per match)
    if (preferences.vibe && preferences.vibe.length > 0) {
      const vibeMatches = restaurant.vibe.filter((v) =>
        preferences.vibe!.some((pref) =>
          v.toLowerCase().includes(pref.toLowerCase()) ||
          pref.toLowerCase().includes(v.toLowerCase())
        )
      );
      score += vibeMatches.length * 2;
    }

    // Dietary matching (+2 per match)
    if (preferences.dietary && preferences.dietary.length > 0) {
      const dietaryMatches = restaurant.dietary.filter((d) =>
        preferences.dietary!.some((pref) =>
          d.toLowerCase().includes(pref.toLowerCase()) ||
          pref.toLowerCase().includes(d.toLowerCase())
        )
      );
      score += dietaryMatches.length * 2;
    }

    // Budget matching (+3 for exact match)
    if (preferences.budget) {
      if (restaurant.price === preferences.budget) {
        score += 3;
      }
    }

    // Location matching (+2 for city, +3 for area)
    if (preferences.location) {
      const locationLower = preferences.location.toLowerCase();
      if (restaurant.city.toLowerCase().includes(locationLower) ||
          locationLower.includes(restaurant.city.toLowerCase())) {
        score += 2;
      }
      if (restaurant.area.toLowerCase().includes(locationLower) ||
          locationLower.includes(restaurant.area.toLowerCase())) {
        score += 3;
      }
    }

    // Rating weight (multiply by rating, then add)
    score += restaurant.rating * 0.5;

    // Bonus for booking availability (+1)
    if (restaurant.bookingAvailable) {
      score += 1;
    }

    return {
      restaurant,
      score: Math.round(score * 100) / 100, // Round to 2 decimal places
    };
  });

  // Sort by score descending and return top 5
  return candidates
    .sort((a, b) => b.score - a.score)
    .slice(0, 5);
}
